# Generated by Django 2.2.16 on 2020-12-20 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20201216_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 16, 43, 5, 154073), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 16, 43, 5, 155071), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100, verbose_name='Имя')),
                ('rnumber', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('remail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('rdate', models.DateField(verbose_name='Дата')),
                ('rtime', models.TimeField(verbose_name='Время')),
                ('rcount', models.CharField(max_length=100, verbose_name='Количество человек')),
                ('rauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Запись',
                'db_table': 'Register',
                'ordering': ['rdate'],
            },
        ),
    ]
