# Generated by Django 2.2.16 on 2020-12-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201220_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 17, 25, 56, 75528), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 17, 25, 56, 76526), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='register',
            table='Запись',
        ),
    ]
