# Generated by Django 2.2.16 on 2020-12-20 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201220_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 17, 27, 27, 909442), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 17, 27, 27, 909442), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
