# Generated by Django 2.2.16 on 2020-12-20 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201220_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ready',
            field=models.CharField(default='0', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 19, 12, 41, 430844), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 20, 19, 12, 41, 430844), verbose_name='Дата'),
        ),
    ]
